package com.a116042018022.greendao.entity.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.a116042018022.greendao.entity.greendao.WisdomEntity;
import com.a116042018022.greendao.entity.greendao.CET4Entity;

import com.a116042018022.greendao.entity.greendao.WisdomEntityDao;
import com.a116042018022.greendao.entity.greendao.CET4EntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig wisdomEntityDaoConfig;
    private final DaoConfig cET4EntityDaoConfig;

    private final WisdomEntityDao wisdomEntityDao;
    private final CET4EntityDao cET4EntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        wisdomEntityDaoConfig = daoConfigMap.get(WisdomEntityDao.class).clone();
        wisdomEntityDaoConfig.initIdentityScope(type);

        cET4EntityDaoConfig = daoConfigMap.get(CET4EntityDao.class).clone();
        cET4EntityDaoConfig.initIdentityScope(type);

        wisdomEntityDao = new WisdomEntityDao(wisdomEntityDaoConfig, this);
        cET4EntityDao = new CET4EntityDao(cET4EntityDaoConfig, this);

        registerDao(WisdomEntity.class, wisdomEntityDao);
        registerDao(CET4Entity.class, cET4EntityDao);
    }
    
    public void clear() {
        wisdomEntityDaoConfig.clearIdentityScope();
        cET4EntityDaoConfig.clearIdentityScope();
    }

    public WisdomEntityDao getWisdomEntityDao() {
        return wisdomEntityDao;
    }

    public CET4EntityDao getCET4EntityDao() {
        return cET4EntityDao;
    }

}
